apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1.${CLUSTER_NAME}.${BASE_DOM}
          - worker-2.${CLUSTER_NAME}.${BASE_DOM}
          - worker-3.${CLUSTER_NAME}.${BASE_DOM}
  storageClassDevices:
    - storageClassName: "lo-blk"
      volumeMode: Block
      devicePaths:
        - /dev/vdc
