apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.2.30:3260
     iqn: iqn.2025-02.com.example:ocp
     lun: 0
     fsType: 'xfs'
